version: 0.2

phases:
  install:
    commands:
      - yum install -y python36 python36-devel python36-pip python36-setuptools python36-virtualenv zip unzip
  pre_build:
    commands:
      - python36 -m virtualenv venv
      - source venv/bin/activate
      - pip install -U pip
      - pip install -r requirements.txt
      - invoke test
  build:
    commands:
      - invoke deploy
      - invoke release --description "$CODEBUILD_SOURCE_VERSION"
artifacts:
  files:
    - dist/*.zip
  discard-paths: yes
